# Generated by Django 5.0.7 on 2024-07-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('red', models.IntegerField()),
                ('black', models.IntegerField()),
                ('green', models.IntegerField()),
                ('even_steve', models.IntegerField()),
                ('odd_todd', models.IntegerField()),
                ('_112', models.IntegerField()),
                ('_212', models.IntegerField()),
                ('_312', models.IntegerField()),
                ('_118', models.IntegerField()),
                ('_1936', models.IntegerField()),
                ('_col1', models.IntegerField()),
                ('_col2', models.IntegerField()),
                ('_col3', models.IntegerField()),
                ('_00', models.IntegerField()),
                ('_0', models.IntegerField()),
                ('_1', models.IntegerField()),
                ('_2', models.IntegerField()),
                ('_3', models.IntegerField()),
                ('_4', models.IntegerField()),
                ('_5', models.IntegerField()),
                ('_6', models.IntegerField()),
                ('_7', models.IntegerField()),
                ('_8', models.IntegerField()),
                ('_9', models.IntegerField()),
                ('_10', models.IntegerField()),
                ('_11', models.IntegerField()),
                ('_12', models.IntegerField()),
                ('_13', models.IntegerField()),
                ('_14', models.IntegerField()),
                ('_15', models.IntegerField()),
                ('_16', models.IntegerField()),
                ('_17', models.IntegerField()),
                ('_18', models.IntegerField()),
                ('_19', models.IntegerField()),
                ('_20', models.IntegerField()),
                ('_21', models.IntegerField()),
                ('_22', models.IntegerField()),
                ('_23', models.IntegerField()),
                ('_24', models.IntegerField()),
                ('_25', models.IntegerField()),
                ('_26', models.IntegerField()),
                ('_27', models.IntegerField()),
                ('_28', models.IntegerField()),
                ('_29', models.IntegerField()),
                ('_30', models.IntegerField()),
                ('_31', models.IntegerField()),
                ('_32', models.IntegerField()),
                ('_33', models.IntegerField()),
                ('_34', models.IntegerField()),
                ('_35', models.IntegerField()),
                ('_36', models.IntegerField()),
                ('_left', models.IntegerField()),
                ('_right', models.IntegerField()),
                ('_q1', models.IntegerField()),
                ('_q2', models.IntegerField()),
                ('_q3', models.IntegerField()),
                ('_q4', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
